### ISSUE TITLE
No need to wait for data after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [sparkfun/BMP180_Breakout#10]
See : https://github.com/sparkfun/BMP180_Breakout_Arduino_Library/issues/3

**Comment by Grahldg** [comment]
Thank you for bringing this to our attention.  Unfortunately this product is retired.  The repository will remain available as an archive for reference, but will no longer be maintained.  If you have further questions about this product please refer to our [forum](https://forum.sparkfun.com).
