### ISSUE TITLE
how to add 2 bmp180 sensors to one arduino board?

### ISSUE THREAD

**Issue by mkahali** [sparkfun/BMP180_Breakout#2]
Hi,

I need to add 2 BMP180 pressure sensor to one arduino board.
sensors will place in different pressure conditions.
Would you please tell me which changes should be done in the program to read data from both simultaneously?
in case of hardware, to which pins the second one should be connected?
I connected 1 sensor and read the measurement.

**Comment by WinniePough** [comment]
It would seem to me that an un-powered I2C module could not answer when being addressed.
It would also seem logical that an un-powered I2C module would not keep any other module from functioning.  So the easy solution is aught to be to alternately power the two modules and separate the response as separate variables in the software.

**Comment by mahfuz195** [comment]
from my knowledge ,what i understand is that  it depends on your implementation and your system setup.Some sensors have some initial startup time before communicating in I2C and if you use tun off/on Vdd method then volatile registers value will be lost(e.g. for bmp180 accuracy level register value.)for BMP180 if you use MUX , then this algorithm you can you1. Start bmp180 sensor#1 measuring pressure data.2. Switch MUX and bmp180 sensor#2 measuring pressure data.3. Swithc MUX and read pressure from bmp180 sensor#1.4. Switch MUX and read pressure from bmp180 sensor#2with this algorithm we can get both pressure data which is measured in almost same time-stamp.
 Kind Regards,Md. Mhafuzul Islam

 


     On Monday, September 28, 2015 1:52 AM, WinniePough <notifications@github.com> wrote:
   

 It would seem to me that an un-powered I2C module could not answer when being addressed.
It would also seem logical that an un-powered I2C module would not keep any other module from functioning. So the easy solution is aught to be to alternately power the two modules and separate the response as separate variables in the software. —
