### ISSUE TITLE
Minimal change in pressure & no change in altitude

### ISSUE THREAD

**Issue by gioalex** [sparkfun/BMP180_Breakout#3]
I've tried this drive but I get some problem with calculated value as described in the object.
I'm trying to understand if there are some casting problem.

Best regards
Alessandro

**Comment by ToniCorinne** [comment]
Sorry for the delayed response @gioalex . If you are still having problems, please try updating to the most recent version of the library. If that does not fix the issue, please provide more information regarding what code you are using, what results you are getting, and what your circuit looks like. Thanks!
