### ISSUE TITLE
Can you send the data from 1 BMP180 sensor to 2 different Arduino Unos?

### ISSUE THREAD

**Issue by pradk1** [sparkfun/BMP180_Breakout#4]
Can you send the data from 1 BMP180 sensor to 2 different Arduino Unos? This is so I can simulate the data in 2 different ways using 2 different serial ports. There would only by 1 3.3V power supply and the grounds would all be connected together properly, but the SDA and SCL pins would be connected to both Arduino Unos on the same pins (A4 & A5). I'm not sure if it's possible, but I thought I would ask. Thank you!

**Comment by arashmarzi** [comment]
What if the scenario is that you have a Raspberry Pi that is the master, an Arduino Micro is a slave to the Pi, and the BMP180 that is a slave to the Micro, so something like this:
Pi (gets data from) <-- Arduino (gets data from) <-- BMP180 (collects data)

would this be possible?

**Comment by mgrusin** [comment]
You may be overcomplicating things. The data you get from the BMP180 is what it is, and would be the same for both Arduinos. How about having one Arduino retrieve the raw data, process the data both ways, and send one result to the hardware serial port, and the other result to a software serial port?

**Comment by ToniCorinne** [comment]
Closing this issue out as two possible fixes have been addressed. Please reopen if you have additional questions.
