### ISSUE TITLE
Json line that goes in preferences

### ISSUE THREAD

**Issue by tytower** [sparkfun/BMP180_Breakout#8]
I did not see that anywhere . Is the only way to download the library via the zip file?

**Comment by ToniCorinne** [comment]
If you would like to fork the library, you can do so [here](https://github.com/sparkfun/BMP180_Breakout_Arduino_Library). You can also download the library.zip there as well.

We had to split our libraries out for inclusion in the Arduino library manager, and pull them into our product repositories as subtrees.
